import type {ExplorerDashboardItem} from '@/features/explorer/types/explorer.types';

export const explorerDashboardItems: ExplorerDashboardItem[] = [
  {
    id: 'internal-storage',
    categoryId: 'internal-storage',
    title: 'Ana bellek',
    subtitle: 'Yerel kök depolama ve tüm ana klasörler',
    icon: 'storage',
  },
  {
    id: 'downloads',
    categoryId: 'downloads',
    title: 'İndirilenler',
    subtitle: 'İndirilen dosyalar ve paketler',
    icon: 'downloads',
  },
  {
    id: 'documents',
    categoryId: 'documents',
    title: 'Belgeler',
    subtitle: 'Belge klasörleri ve çalışma dosyaları',
    icon: 'documents',
  },
  {
    id: 'images',
    categoryId: 'images',
    title: 'Görüntüler',
    subtitle: 'Fotoğraflar, ekran görüntüleri ve medya',
    icon: 'images',
  },
  {
    id: 'audio',
    categoryId: 'audio',
    title: 'Ses',
    subtitle: 'Müzik, kayıtlar ve ses dosyaları',
    icon: 'audio',
  },
  {
    id: 'video',
    categoryId: 'video',
    title: 'Videolar',
    subtitle: 'Filmler, klipler ve video arşivi',
    icon: 'video',
  },
  {
    id: 'system',
    categoryId: 'system',
    title: 'Sistem',
    subtitle: 'Korunan alanlar için güvenli bilgi ekranı',
    icon: 'system',
  },
  {
    id: 'cloud',
    categoryId: 'cloud',
    title: 'Bulut',
    subtitle: 'Uzak sağlayıcılar ve bağlı hesaplar',
    icon: 'cloud',
  },
  {
    id: 'network',
    categoryId: 'network',
    title: 'Ağdan erişim',
    subtitle: 'SMB, WebDAV ve LAN paylaşım noktaları',
    icon: 'network',
  },
  {
    id: 'trash',
    categoryId: 'trash',
    title: 'Geri Dönüşüm',
    subtitle: 'Silinen içerikler için güvenli placeholder',
    icon: 'trash',
  },
  {
    id: 'apps',
    categoryId: 'apps',
    title: 'Uygulamalar',
    subtitle: 'APK ve uygulama paketleri için bilgi ekranı',
    icon: 'apps',
  },
  {
    id: 'recent',
    categoryId: 'recent',
    title: 'Yeni dosyalar',
    subtitle: 'Yakın zamanda eklenen veya güncellenen içerikler',
    icon: 'recent',
  },
];
